### ISSUE TITLE
what about 'Enter verification code'?

### ISSUE THREAD

**Issue by xiuxiuxius** [LuongTanDat/AlphaPose-Cpp#2]
你好，谢谢你的开源。我在执行“dev pull”时，提示我需要验证码，请问验证码是多少呢？
hello，thanks for your code. But when I execute "dev pull"，it ask for "Enter verification code" as follows:
![image](https://user-images.githubusercontent.com/89114157/145173242-57542129-1a31-45bd-882c-40707d14c13e.png)

**Comment by datlt4** [comment]
I am uploading models to google drive, you can download directly from above links, wait about 10mins for uploading is accomplished:
https://drive.google.com/drive/folders/1TNIN0_SrPVooRLX42QlvuafY37zqo0y7?usp=sharing
https://drive.google.com/drive/folders/1Q8VW9BoldAoDqZ7n-3z2BDr1Am29Z7CA?usp=sharing

**Comment by xiuxiuxius** [comment]
oooh，thanks for  your reply. I have transfered successfully. thanks all the same. ^_^
